apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Pod
metadata:
  name: mysql
  labels:
    app: mysql
  spec:
    containers:
      - name: mysql
        image: michaelacook1/db
      env:
      - name: MYSQL_DB
        value: "board_db"
      - name: MYSQL_ROOT_PASSWORD
        valueFrom:
          secretKeyref:
           name: secretkey
           key: itsasecret
      ports:
      - containerPort: 3306
        
       